# dbt_project.yml

name: 'event_analytics'
version: '1.0.0'
profile: 'event_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# Disable quoting globally
quoting:
  database: false
  schema: false
  identifier: false

models:
  event_analytics:

    # Bronze layer → source models
    source:
      +schema: bronze
      +materialized: view
      +docs:
        node_color: "#cd7f32"   # Bronze (brownish)

    # Silver layer → staging models
    staging:
      +schema: silver
      +materialized: incremental
      +docs:
        node_color: "#555555"   # Silver (gray)

    # Gold layer → end products
    end_products:
      +schema: gold
      +materialized: table
      +docs:
        node_color: "#ffd700"   # gold
